CREATE TABLE asiakas (
	id INTEGER NOT NULL, 
	etunimi VARCHAR(144) NOT NULL, 
	sukunimi VARCHAR(144) NOT NULL, 
	login VARCHAR(144) NOT NULL, 
	salasana VARCHAR(144) NOT NULL, 
	PRIMARY KEY (id)
)
CREATE TABLE kurssi (
	id INTEGER NOT NULL, 
	kuvaus VARCHAR(144) NOT NULL, 
	aika DATETIME NOT NULL, 
	kesto INTEGER NOT NULL, 
	PRIMARY KEY (id)
)
CREATE TABLE ohjaaja (
	id INTEGER NOT NULL, 
	etunimi VARCHAR(144) NOT NULL, 
	sukunimi VARCHAR(144) NOT NULL, 
	login VARCHAR(144) NOT NULL, 
	salasana VARCHAR(144) NOT NULL, 
	PRIMARY KEY (id)